collections:
  - name: azure.azcollection
    version: '>=1.11.0'
  - name: amazon.aws
    version: '>=2.0.0'
  - name: ansible.windows
    version: '>=1.10.0'
  - name: ansible.posix
    version: '>=1.4.0'
